apiVersion: v2
version: 0.0.1-devel
description: This chart creates test resources for newrelic-prometheus-agent.
name: test-resources

maintainers:
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: csongnr
    url: https://github.com/csongnr
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
