apiVersion: v2
version: 0.0.1-devel
description: This chart creates test resources for newrelic-prometheus-agent.
name: test-resources

maintainers:
  - name: nserrino
    url: https://github.com/nserrino
  - name: philkuz
    url: https://github.com/philkuz
  - name: htroisi
    url: https://github.com/htroisi
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: svetlanabrennan
    url: https://github.com/svetlanabrennan
  - name: nrepai
    url: https://github.com/nrepai
  - name: csongnr
    url: https://github.com/csongnr
  - name: vuqtran88
    url: https://github.com/vuqtran88
  - name: xqi-nr
    url: https://github.com/xqi-nr
