apiVersion: v2
name: newrelic-prometheus
description: A Helm chart to deploy Prometheus.

type: application

version: 0.0.13-devel

# Prometheus Server Version
appVersion: "v2.37.0"
annotations:
# TODO replace with the first configurator release
  configuratorVersion: "main"

dependencies:
  - name: common-library
    version: 1.0.6
    repository: "https://helm-charts.newrelic.com"

keywords:
  - newrelic
  - prometheus

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: carlossscastro
    url: https://github.com/carlossscastro
  - name: sigilioso
    url: https://github.com/sigilioso
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: marcsanmi
    url: https://github.com/marcsanmi
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
  - name: roobre
    url: https://github.com/roobre
