apiVersion: apps/v1 
kind: Deployment
metadata:
  name: avalanche
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: {{ .Values.avalanche.replicas }}
  template:
    metadata:
      labels:
        app: avalanche
      {{- with .Values.avalanche.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: pg-avalanche
        image: quay.io/freshtracks.io/avalanche:latest
        args:
        {{- with .Values.avalanche.config }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 9001
