kind: ConfigMap
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
apiVersion: v1
data:
  config.yaml: |-
    # Configuration for newrelic-prometheus-configurator
    data_source_name: {{ include "newrelic.common.cluster" . }}
    newrelic_remote_write:
    {{- with (include "newrelic-prometheus.configurator.remote_write" . ) -}}
      {{- . | nindent 6 }}
    {{- end -}}
    {{- with (include "newrelic-prometheus.configurator.extra_remote_write" . ) -}}
    {{- . | nindent 4 }}
    {{- end -}}
    {{- with (include "newrelic-prometheus.configurator.static_targets" . ) -}}
    {{- . | nindent 4 }}
    {{- end -}}
    {{- with (include "newrelic-prometheus.configurator.extra_scrape_configs" . ) -}}
    {{- . | nindent 4 }}
    {{- end -}}
    {{- with (include "newrelic-prometheus.configurator.common" . ) -}}
    {{- . | nindent 4 }}
    {{- end -}}
