kind: ConfigMap
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
apiVersion: v1
data:
  config.yaml: |
    # configurator config
