name: E2E over minikube (Internal Contribution)

on:
  pull_request:
  push:
    branches:
      - main
      - renovate/**

permissions:
  contents: read

env:
  LATEST_K8S_VERSION: 'v1.36.0'
  MINIKUBE_VERSION: 'v1.39.0'
  DOCKER_API_VERSION: '1.44'

jobs:
  e2e-test:
    name: Run E2E Tests
    # Do not run e2e tests if PR has skip-e2e label or if it's from a forked repo (external contribution)
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci/skip-e2e') && github.event.pull_request.head.repo.full_name == 'newrelic/newrelic-prometheus-configurator' }}
    runs-on: ubuntu-latest
    # If the environment is broken this job could timeout since the default timeout for tilt ci is 30m.
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Install Minikube
        uses: medyagh/setup-minikube@latest
        with:
          start: 'false'
          minikube-version: ${{ env.MINIKUBE_VERSION }}
          driver: 'docker'
      - name: Install ctlptl
        run: |
          CTLPTL_VERSION="0.9.6"
          curl -fsSL https://github.com/tilt-dev/ctlptl/releases/download/v$CTLPTL_VERSION/ctlptl.$CTLPTL_VERSION.linux.x86_64.tar.gz | sudo tar -xzv -C /usr/local/bin ctlptl
      - name: Install Tilt
        run: |
          TILT_VERSION="0.37.7"
          curl -fsSL https://github.com/tilt-dev/tilt/releases/download/v$TILT_VERSION/tilt.$TILT_VERSION.linux.x86_64.tar.gz | tar -xzv tilt && sudo mv tilt /usr/local/bin/tilt
      - name: Start Minikube
        run: |
          ctlptl create cluster minikube --registry=ctlptl-registry --kubernetes-version=${{ env.MINIKUBE_VERSION }}

      - name: Run e2e-test
        uses: newrelic/newrelic-integration-e2e-action@v1
        with:
          retry_seconds: 90
          retry_attempts: 5
          agent_enabled: false
          spec_path: test/e2e/test-specs.yml
          account_id: ${{ secrets.K8S_AGENTS_E2E_ACCOUNT_ID }}
          api_key: ${{ secrets.K8S_AGENTS_E2E_API_KEY }}
          license_key: ${{ secrets.K8S_AGENTS_E2E_LICENSE_KEY }}
